FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir \
    --default-timeout=300 \
    --retries=10 \
    -i https://mirrors.aliyun.com/pypi/simple/ \
    -r requirements.txt

COPY apps/split_bot/ /app/
COPY shared /app/shared

CMD ["python", "main.py"]

